//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicLinkCGM.MagoEasyLookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MagoEasyLookService.EasyLookServiceSoap")]
    public interface EasyLookServiceSoap {
        
        // CODEGEN: Generating message contract since element name authenticationToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReport", ReplyAction="*")]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse XmlExecuteReport(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReport", ReplyAction="*")]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse> XmlExecuteReportAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReportWithNotValidFields", ReplyAction="*")]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse XmlExecuteReportWithNotValidFields(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReportWithNotValidFields", ReplyAction="*")]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse> XmlExecuteReportWithNotValidFieldsAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReportEI", ReplyAction="*")]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse XmlExecuteReportEI(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlExecuteReportEI", ReplyAction="*")]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse> XmlExecuteReportEIAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PdfExecuteReport", ReplyAction="*")]
        MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse PdfExecuteReport(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PdfExecuteReport", ReplyAction="*")]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse> PdfExecuteReportAsync(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlGetParameters", ReplyAction="*")]
        MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse XmlGetParameters(MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlGetParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse> XmlGetParametersAsync(MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReport", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequestBody Body;
        
        public XmlExecuteReportRequest() {
        }
        
        public XmlExecuteReportRequest(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime applicationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatedUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool useApproximation;
        
        public XmlExecuteReportRequestBody() {
        }
        
        public XmlExecuteReportRequestBody(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            this.authenticationToken = authenticationToken;
            this.parameters = parameters;
            this.applicationDate = applicationDate;
            this.impersonatedUser = impersonatedUser;
            this.useApproximation = useApproximation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponseBody Body;
        
        public XmlExecuteReportResponse() {
        }
        
        public XmlExecuteReportResponse(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportResult;
        
        public XmlExecuteReportResponseBody() {
        }
        
        public XmlExecuteReportResponseBody(MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportResult) {
            this.XmlExecuteReportResult = XmlExecuteReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportWithNotValidFieldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReportWithNotValidFields", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequestBody Body;
        
        public XmlExecuteReportWithNotValidFieldsRequest() {
        }
        
        public XmlExecuteReportWithNotValidFieldsRequest(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportWithNotValidFieldsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime applicationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatedUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool useApproximation;
        
        public XmlExecuteReportWithNotValidFieldsRequestBody() {
        }
        
        public XmlExecuteReportWithNotValidFieldsRequestBody(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            this.authenticationToken = authenticationToken;
            this.parameters = parameters;
            this.applicationDate = applicationDate;
            this.impersonatedUser = impersonatedUser;
            this.useApproximation = useApproximation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportWithNotValidFieldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReportWithNotValidFieldsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponseBody Body;
        
        public XmlExecuteReportWithNotValidFieldsResponse() {
        }
        
        public XmlExecuteReportWithNotValidFieldsResponse(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportWithNotValidFieldsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportWithNotValidFieldsResult;
        
        public XmlExecuteReportWithNotValidFieldsResponseBody() {
        }
        
        public XmlExecuteReportWithNotValidFieldsResponseBody(MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportWithNotValidFieldsResult) {
            this.XmlExecuteReportWithNotValidFieldsResult = XmlExecuteReportWithNotValidFieldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportEIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReportEI", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequestBody Body;
        
        public XmlExecuteReportEIRequest() {
        }
        
        public XmlExecuteReportEIRequest(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportEIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime applicationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatedUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool useApproximation;
        
        public XmlExecuteReportEIRequestBody() {
        }
        
        public XmlExecuteReportEIRequestBody(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            this.authenticationToken = authenticationToken;
            this.parameters = parameters;
            this.applicationDate = applicationDate;
            this.impersonatedUser = impersonatedUser;
            this.useApproximation = useApproximation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlExecuteReportEIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlExecuteReportEIResponse", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponseBody Body;
        
        public XmlExecuteReportEIResponse() {
        }
        
        public XmlExecuteReportEIResponse(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlExecuteReportEIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportEIResult;
        
        public XmlExecuteReportEIResponseBody() {
        }
        
        public XmlExecuteReportEIResponseBody(MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportEIResult) {
            this.XmlExecuteReportEIResult = XmlExecuteReportEIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PdfExecuteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PdfExecuteReport", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequestBody Body;
        
        public PdfExecuteReportRequest() {
        }
        
        public PdfExecuteReportRequest(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PdfExecuteReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime applicationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatedUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool useApproximation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string diagnostic;
        
        public PdfExecuteReportRequestBody() {
        }
        
        public PdfExecuteReportRequestBody(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation, string diagnostic) {
            this.authenticationToken = authenticationToken;
            this.parameters = parameters;
            this.applicationDate = applicationDate;
            this.impersonatedUser = impersonatedUser;
            this.useApproximation = useApproximation;
            this.diagnostic = diagnostic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PdfExecuteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PdfExecuteReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponseBody Body;
        
        public PdfExecuteReportResponse() {
        }
        
        public PdfExecuteReportResponse(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PdfExecuteReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] PdfExecuteReportResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string diagnostic;
        
        public PdfExecuteReportResponseBody() {
        }
        
        public PdfExecuteReportResponseBody(byte[] PdfExecuteReportResult, string diagnostic) {
            this.PdfExecuteReportResult = PdfExecuteReportResult;
            this.diagnostic = diagnostic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlGetParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlGetParameters", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequestBody Body;
        
        public XmlGetParametersRequest() {
        }
        
        public XmlGetParametersRequest(MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlGetParametersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime applicationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatedUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool useApproximation;
        
        public XmlGetParametersRequestBody() {
        }
        
        public XmlGetParametersRequestBody(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            this.authenticationToken = authenticationToken;
            this.parameters = parameters;
            this.applicationDate = applicationDate;
            this.impersonatedUser = impersonatedUser;
            this.useApproximation = useApproximation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlGetParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlGetParametersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponseBody Body;
        
        public XmlGetParametersResponse() {
        }
        
        public XmlGetParametersResponse(MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlGetParametersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlGetParametersResult;
        
        public XmlGetParametersResponseBody() {
        }
        
        public XmlGetParametersResponseBody(string XmlGetParametersResult) {
            this.XmlGetParametersResult = XmlGetParametersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EasyLookServiceSoapChannel : MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EasyLookServiceSoapClient : System.ServiceModel.ClientBase<MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap>, MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap {
        
        public EasyLookServiceSoapClient() {
        }
        
        public EasyLookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EasyLookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasyLookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasyLookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReport(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest request) {
            return base.Channel.XmlExecuteReport(request);
        }
        
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReport(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse retVal = ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReport(inValue);
            return retVal.Body.XmlExecuteReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse> MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReportAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest request) {
            return base.Channel.XmlExecuteReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportResponse> XmlExecuteReportAsync(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            return ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReportWithNotValidFields(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest request) {
            return base.Channel.XmlExecuteReportWithNotValidFields(request);
        }
        
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportWithNotValidFields(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse retVal = ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReportWithNotValidFields(inValue);
            return retVal.Body.XmlExecuteReportWithNotValidFieldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse> MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReportWithNotValidFieldsAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest request) {
            return base.Channel.XmlExecuteReportWithNotValidFieldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsResponse> XmlExecuteReportWithNotValidFieldsAsync(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportWithNotValidFieldsRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            return ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReportWithNotValidFieldsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReportEI(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest request) {
            return base.Channel.XmlExecuteReportEI(request);
        }
        
        public MagicLinkCGM.MagoEasyLookService.ArrayOfString XmlExecuteReportEI(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse retVal = ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReportEI(inValue);
            return retVal.Body.XmlExecuteReportEIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse> MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlExecuteReportEIAsync(MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest request) {
            return base.Channel.XmlExecuteReportEIAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIResponse> XmlExecuteReportEIAsync(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlExecuteReportEIRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            return ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlExecuteReportEIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.PdfExecuteReport(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest request) {
            return base.Channel.PdfExecuteReport(request);
        }
        
        public byte[] PdfExecuteReport(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation, ref string diagnostic) {
            MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest inValue = new MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            inValue.Body.diagnostic = diagnostic;
            MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse retVal = ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).PdfExecuteReport(inValue);
            diagnostic = retVal.Body.diagnostic;
            return retVal.Body.PdfExecuteReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse> MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.PdfExecuteReportAsync(MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest request) {
            return base.Channel.PdfExecuteReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.PdfExecuteReportResponse> PdfExecuteReportAsync(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation, string diagnostic) {
            MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest inValue = new MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.PdfExecuteReportRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            inValue.Body.diagnostic = diagnostic;
            return ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).PdfExecuteReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlGetParameters(MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest request) {
            return base.Channel.XmlGetParameters(request);
        }
        
        public string XmlGetParameters(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse retVal = ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlGetParameters(inValue);
            return retVal.Body.XmlGetParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse> MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap.XmlGetParametersAsync(MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest request) {
            return base.Channel.XmlGetParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagicLinkCGM.MagoEasyLookService.XmlGetParametersResponse> XmlGetParametersAsync(string authenticationToken, string parameters, System.DateTime applicationDate, string impersonatedUser, bool useApproximation) {
            MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest inValue = new MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequest();
            inValue.Body = new MagicLinkCGM.MagoEasyLookService.XmlGetParametersRequestBody();
            inValue.Body.authenticationToken = authenticationToken;
            inValue.Body.parameters = parameters;
            inValue.Body.applicationDate = applicationDate;
            inValue.Body.impersonatedUser = impersonatedUser;
            inValue.Body.useApproximation = useApproximation;
            return ((MagicLinkCGM.MagoEasyLookService.EasyLookServiceSoap)(this)).XmlGetParametersAsync(inValue);
        }
    }
}
